### PR TITLE
Surf webpage

### PR DESCRIPTION
**Pull request by claudia1201**
Here is my surf webpage. I made the mistake of creating the html and css while Chrome was in 25% zoom, so every time I zoom in everything kind of goes out of order. I tried searching a solution in google but everything i tried just works for some stuff but not for the whole thing.

### CODE REVIEW

**Comment by claudia1201** [comment]
i tried default zoom in CSS
putting everything in percentage
But like I said it only works for some stuff.

**Comment by kylehill** [comment]
Gotcha. Yeah, that kinda sucks -- when you zoom Chrome out to 25% it does look really good, and your HTML is nice and clean too.

I'm going stick a "Needs Review" on this assignment because it should just be the matter of downscaling some CSS font-sizes and line-heights; this is potentially a big part of your portfolio, and I'd hate to see you not want to use it just because of a few CSS bugs. It shouldn't take that long to fix.

**Comment by claudia1201** [comment]
just updated the CSS. please let me know if I can improve something else!
Thank you!

**Comment by kylehill** [comment]
Looking great! Well done.

**Pull request closed without merging**
